---
# Every test file has one or more tests...
test_name: Test rest-api

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: Make sure we have the right ID

    # Define the request to be made...
    request:
      url: "curl -i http://localhost:5000/todo/api/v1.0/tasks"
      method: GET

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        id: 1